// ERROR ACTIONS
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const UPDATE_ERRORS = 'UPDATE_ERRORS';

// AUTH ACTIONS
export const UPDATE_TOKEN = 'UPDATE_TOKEN';

// PROFILE ACTIONS
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const STORE_PROFILE = 'STORE_PROFILE';

// USER ACTIONS
export const LOAD_USERS = 'LOAD_USERS';
export const STORE_USERS = 'STORE_USERS';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const REPLACE_USER = 'REPLACE_USER';
export const DELETE_USER = 'DELETE_USER';

// CATEGORY ACTIONS
export const STORE_CATEGORIES = 'STORE_CATEGORIES';
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

// TYPE ACTIONS
export const LOAD_TYPES = 'LOAD_TYPES';
export const REPLACE_TYPE = 'REPLACE_TYPE';

// VARIABLE ACTIONS
export const REPLACE_VARIABLES = 'REPLACE_VARIABLES';
export const REPLACE_VARIABLE = 'REPLACE_VARIABLE';

// CATEGORY TYPE ACTIONS
export const LOAD_CATEGORY_TYPES = 'LOAD_CATEGORY_TYPES';
export const REPLACE_CATEGORY_TYPES = 'REPLACE_CATEGORY_TYPES';
